Add GivBacksRelayer contract
Giveth/giv-token-contracts pull request #51
Opened 2022-01-20 16:33 UTC by paxthemax

# GivBacksRelayer contract

This contract relays the `sendGIVbacks` call from a `distributor` to a `TokenDistro`.

2022-01-20 16:44 UTC, sembrestels reviewed
It looks fantastic, I just left two suggestions of things you may want to change.

2022-01-20 16:44 UTC, sembrestels commented on contracts/GivBacksRelayer/GIVBacksRelayer.sol
> +        emit CreatedBatches(msg.sender);
There is no way to ask the contract which are the batches that have been introduced, and I think they could be emitted here.

2022-01-20 16:51 UTC, paxthemax commented on contracts/GivBacksRelayer/GIVBacksRelayer.sol
> +    function createBatches(bytes32[] calldata batches)
I think i prefer `addBatches` since we do not really have explicit rounds being tracked.

2022-01-20 17:26 UTC, sembrestels reviewed
The code looks great :heart_eyes:

2022-01-20 17:30 UTC, sembrestels commented
> This way, we can **explicitly** track the nonce of each batch for execution.

I think this is a great idea, way more convenient!

2022-01-24 17:20 UTC, paxthemax commented
I think this is ready to go basically.

2022-01-31 07:43 UTC, aminlatifi requested changes
@paxthemax I have not finished my review. Most of them are typos, but one is initialize function name which is important and decided to report fast

2022-01-31 07:43 UTC, aminlatifi commented on contracts/Interfaces/IGIVBacksRelayer.sol
> +     * @param batch - A list of batches that can be executed
```suggestion
     * @param batch - A batch that can be executed
```

2022-01-31 07:43 UTC, aminlatifi commented on contracts/Interfaces/IGIVBacksRelayer.sol
> +     * @dev This funciton will try and execute a batch.
```suggestion
     * @dev This function will try and execute a batch.
```

2022-01-31 07:43 UTC, aminlatifi commented on contracts/Interfaces/IGIVBacksRelayer.sol
> +     * @param _nonce - Nonce to prevent batch collisons
```suggestion
     * @param _nonce - Nonce to prevent batch collisions
```

2022-01-31 07:43 UTC, aminlatifi commented on contracts/GivBacksRelayer/GIVBacksRelayer.sol
> +     * @dev Intialize the relayer.
```suggestion
     * @dev Initialize the relayer.
```

2022-01-31 07:43 UTC, aminlatifi commented on contracts/GivBacksRelayer/GIVBacksRelayer.sol
> +    function intialize(address _tokenDistroContract, address batcher)
```suggestion
    function initialize(address _tokenDistroContract, address batcher)
```

@paxthemax Let's add upgradability test for this contract too

2022-01-31 13:45 UTC, aminlatifi commented
Thank you @paxthemax, it looks great with well-implemented tests.

2022-02-04 14:12 UTC, paxthemax commented
Added a basic deployment script.

2022-03-01 12:21 UTC, mohammadranjbarz commented
Now the generated code of my scripts is like this
```
"connect 0xA1514067E6fE7919FB239aF5259FfF120902b4f9 token-manager voting:1 act agent:0 0x18a46865AAbAf416a970eaA8625CFC430D2364A1 sendGIVbacks(address[],uint256[]) [0xad9c46a9ab1a96ef80001cc5c153cc4b58232da3,0x826976d7c600d45fb8287ca1d7c76fc8eb732030,0x4ff14c2f19cf78ffd249b22d622e6ee7e25b84d8,0xec952ed8e7c2aa466cac36fd611d2e87df1243d7,0xb7562f12e41c762cecda99d62bd6eac7b0c3b4c1,0x1a7e76c3bc4006e804842c232d91767d3c5299d2,0x77c3db040f79ae46a91529a667c03ab484b37116,0xe4f0e8ae1fd76928a6f586a2ec6a120ccdc50a8e,0x8afc051de5f3941a68d3dbb9c7c96ec773ef494b,0x05903affd45da43a14f9a9421605e0e7a4fe2e21,0x7c5361f5bb5e2bb123c95e69bed331f3b0b8f094,0x29cf75f4622dbedbc63354e28f6e734635690f4b,0x66339e64c3447f32251a3baf79bc7f4192fd1386,0x05a1ff0a32bc24265bcb39499d0c5d9a6cb2011c,0x243f5dead21bd50bad298e0efd5ed0e957e8bf0a,0x2473fb8eebe46041d5f528a728505c26a81c1158] [1352270000000000000000,264279999999999970000,53760000000000000000,37410000000000000000,21380000000000000000,13350000000000000000,8020000000000000000,4810000000000000000,3750000000000000000,3380000000000000000,2610000000000000000,2250000000000000000,830000000000000000,750000000000000000,530000000000000000,310000000000000000]"
```

Please ping me after it need changes ,and tell me what it should be like

@divine-comedian  I didn't know who is responsible and knows the format, so I mentioned you here

2022-04-27 12:20 UTC, paxthemax reviewed
This is a small change, LGTM

2022-05-24 23:29 UTC, laurenluz commented
can we close this?

2024-04-17 15:59 UTC, closed without merging